enum CommandsSignal {
  ARM_CHECK_STATUS = 3,
  ARM_STATUS = 4,
  ARM_CONNECT = 5,
  ARM_CONNECTED = 6,
  ARM_MOVE_TO_POINT = 7,
  ARM_APPLY_TRAJECTORY = 8,
  ARM_CANCEL_TRAJECTORY = 9,
  ARM_CANCELED_TRAJECTORY = 10,
  ARM_DISCONNECT = 11,
  ARM_DISCONNECTED = 12,
  ARM_HOME_SEARCHED = 13,
}
export default CommandsSignal;
