export const METAINFO_TOPIC = 'metainfo';
export const ROBOT_NAME_COMMANDS_TOPIC = 'ROBOT_NAME_commands';
export const ROBOT_NAME_MOVED_TOPIC = 'ROBOT_NAME_moved';

export const ALL_TOPICS = [
  METAINFO_TOPIC,
  ROBOT_NAME_COMMANDS_TOPIC,
  ROBOT_NAME_MOVED_TOPIC,
];
